name: Working with Artifacts
on: 
    workflow_dispatch:   

env:
  build-artifact-key: my-app-${{ github.sha }}
  test-coverage-key: test-coverage-${{ github.sha }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: my-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v4
              with:
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
                path: my-app/node_modules           

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci 
                  
            - name: Build code
              run: npm run build my-app 

            - name: Unit tests
              run: npm run test -- --coverage

            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.build-artifact-key }}
                path: my-app/build
      
            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.test-coverage-key }}
                path: my-app/coverage
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Download build files
            uses: actions/download-artifact@v4
            with:
              name: ${{ env.build-artifact-key }}
              path: build
          - name: Download build files
            uses: actions/download-artifact@v4
            with:
              name: ${{ env.test-coverage-key }}
              path: coverage