name: Working with Artifacts
on: 
    workflow_dispatch:     

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: my-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
           
            - name: install dependencies  
              run: |
                npm ci
                  
            - name: Build code
              run: |
                npm run build

         
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - test-build
        steps:         
            - run: echo "test build"    